title:            Dhruv Bhatia
tagline:          Dhruv's thoughts.
description:      Dhruv Bhatia's blog.
#Comment out url when working locally to resolve base urls correctly
url:              http://dhruvbhatia.com

# Owner/author information
owner:
  name:           Dhruv Bhatia
  avatar:         me.jpg
  bio:            "Whisky drinker, data-driven digital marketer, and technology lover.</p><p>From Melbourne, Australia.</p>"
  email:          dhruv@dhruvbhatia.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        dhruv_au
  facebook:       dhruvb
  github:         dhruvbhatia
  linkedin:       214148056
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    https://plus.google.com/105041616146057386035

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-20416806-1
google_verify:      iIYQhQjWVz5IytKp5Z7AAwhZ-NxUk0kN5EuBoLRLW24
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Thoughts
    url: /thoughts
  - title: Projects
    url: /projects
  # - title: Made Mistakes
  #   url: http://mademistakes.com
  #   external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Australia/Melbourne
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]